/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlnu;

import java.awt.event.ActionEvent;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

import DAO.banDAO;
import DAO.NuocUongDAO;
import DAO.nhanVienDAO;
import DTO.Ban;
import DTO.NuocUong;
import DTO.nhanVien;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.SwingConstants;
import javax.swing.JComboBox;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author hi
 */
public class BanHangFr extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public BanHangFr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbTieude = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        pannelQLnuoc = new javax.swing.JPanel();
        cbbtenNuoc = new javax.swing.JComboBox<>();

        spBangnuoc = new javax.swing.JScrollPane();

        jTable1 = new javax.swing.JTable();

        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    int select = jTable1.getSelectedRow();
                    if (select != -1) {
                        tfSoluong.setText((String) jTable1.getValueAt(select, 1));
                        cbbtenNuoc.setSelectedItem((String) jTable1.getValueAt(select, 0));
                    }
                }

            }
        });
        //  tinh tien nuoc 

        DecimalFormat decimalFormat = new DecimalFormat("#,###");
        cbbtenNuoc.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent d) {
                lbGiaVND.setText("0");
                lbThanhtienVND.setText("0");

                String getTenNuoc = (String) cbbtenNuoc.getSelectedItem();

                if (tfSoluong.getText().isEmpty()) {

                    lbGiaVND.setText("0");
                    lbThanhtienVND.setText("0");
                } else {
                    float soLuong = Float.parseFloat(tfSoluong.getText());
                    float giaBan = Float.parseFloat(String.valueOf(NuocUongDAO.getInstance().selectById(getTenNuoc).getGiaBan()));
                    float thanhTien = soLuong * giaBan;
                    lbGiaVND.setText(String.valueOf(NuocUongDAO.getInstance().selectById(getTenNuoc).getGiaBan()));
                    lbThanhtienVND.setText(decimalFormat.format(thanhTien) + " VNĐ");
                }
            }
        });

        cbbban = new javax.swing.JComboBox<>();
        btnAddnuoc = new javax.swing.JButton();
        tfSoluong = new javax.swing.JTextField();

        //tinh tien nuoc khi go phim
        tfSoluong.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String getTenNuoc = (String) cbbtenNuoc.getSelectedItem();
                float soLuong = Float.parseFloat(tfSoluong.getText());
                float giaBan = Float.parseFloat(String.valueOf(NuocUongDAO.getInstance().selectById(getTenNuoc).getGiaBan()));
                float thanhTien = soLuong * giaBan;

                if (getTenNuoc.equals(null)) {
                    lbGiaVND.setText("0");
                } else {
                    lbGiaVND.setText(String.valueOf(NuocUongDAO.getInstance().selectById(getTenNuoc).getGiaBan()));
                    lbThanhtienVND.setText(decimalFormat.format(thanhTien) + " VNĐ");
                }

            }
        });
        lbSoluong = new javax.swing.JLabel();
        lbGia = new javax.swing.JLabel();
        lbGiaVND = new javax.swing.JLabel();
        lbThanhtien = new javax.swing.JLabel();
        lbThanhtienVND = new javax.swing.JLabel();
        btnFixnuoc = new javax.swing.JButton();
        btnDeletenuoc = new javax.swing.JButton();
        btnResetnuoc = new javax.swing.JButton();
        btnResetnuoc.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                btnReSet(e);
            }
        });

        jPanel3 = new javax.swing.JPanel();

        jPanel4 = new javax.swing.JPanel();
        lbTongtien = new javax.swing.JLabel();
        lbTiennhan = new javax.swing.JLabel();
        lbTienthua = new javax.swing.JLabel();
        lbTongtienVND = new javax.swing.JLabel();
        lbTienthuaVND = new javax.swing.JLabel();
        txtTiennhan = new javax.swing.JTextField();

        txtTiennhan.addKeyListener(new KeyAdapter() {
            public float tongTien;
            public float tienNhan;
            public float tienThua;

            @Override
            public void keyReleased(KeyEvent e) {

                tongTien = Float.parseFloat(lbTongtienVND.getText());

                tienNhan = Float.parseFloat(txtTiennhan.getText());
                tienThua = tienNhan - tongTien;

                if (tienThua < 0) {
                    lbTienthuaVND.setText("Tiền chưa đủ");
                } else {
                    lbTienthuaVND.setText(decimalFormat.format(tienThua) + "  VNĐ");
                }
            }
        });

        btnPay = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbmaSoNV = new javax.swing.JLabel();
        lbHotennhanvien = new javax.swing.JLabel();
        lbNgay = new javax.swing.JLabel();
        lbThoigian = new javax.swing.JLabel();
        lbTrong = new javax.swing.JLabel();
        lbKhachdat = new javax.swing.JLabel();
        lbDacokhach = new javax.swing.JLabel();
        lbDangchon = new javax.swing.JLabel();

        // thiet lap combox drop down list cho ten nuoc
        ArrayList<NuocUong> listDoUong = NuocUongDAO.getInstance().selectAll();
        String[] list = new String[listDoUong.size()];
        for (int i = 0; i < listDoUong.size(); i++) {
            list[i] = listDoUong.get(i).getTenNuoc();
        }
        cbbtenNuoc.setModel(new javax.swing.DefaultComboBoxModel<>(list));

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bán Hàng");

        lbTieude.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbTieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTieude.setText("Quản Lý Bán Hàng");
        lbTieude.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbTieude.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản Lý Bàn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        panel1.setMinimumSize(new java.awt.Dimension(0, 0));
        panel1.setName("");

        lbban1 = new JLabel("Bàn 1");
        lbban1.setFont(new Font("Tahoma", Font.PLAIN, 18));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1Layout.setHorizontalGroup(
                panel1Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(30)
                                .addComponent(lbban1, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(233, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
                panel1Layout.createParallelGroup(Alignment.TRAILING)
                        .addGroup(Alignment.LEADING, panel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbban1)
                                .addContainerGap(407, Short.MAX_VALUE))
        );
        panel1.setLayout(panel1Layout);

        btnAddnuoc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Icon = new ImageIcon("src/main/java/image/add-1-icon.png");
        resizeImg = Icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        resizedIcon = new ImageIcon(resizeImg);
        btnAddnuoc.setIcon(resizedIcon);
//        btnAddnuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-1-icon.png"))); // NOI18N
        btnAddnuoc.setText("Thêm");
        btnAddnuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddnuoc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAddnuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddnuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddnuocActionPerformed(evt);
            }
        });

        tfSoluong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoluongActionPerformed(evt);
            }
        });

        lbSoluong.setBackground(new java.awt.Color(153, 153, 255));
        lbSoluong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSoluong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSoluong.setText("Số lượng");

        lbGia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGia.setText("Cost: ");
        lbGia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbGia.setName(""); // NOI18N

        lbGiaVND.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGiaVND.setText("0");

        lbGiaVND.setToolTipText("");

        lbThanhtien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbThanhtien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThanhtien.setText("Thành tiền:");

        lbThanhtienVND.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThanhtienVND.setText("0 VNĐ");

        btnFixnuoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        btnFixnuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fix.png"))); // NOI18N
        Icon = new ImageIcon("src/main/java/image/fix.png");
        resizeImg = Icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        resizedIcon = new ImageIcon(resizeImg);
        btnFixnuoc.setIcon(resizedIcon);
        btnFixnuoc.setText("Sửa");
        btnFixnuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFixnuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFixnuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixnuocActionPerformed(evt);
            }
        });

        btnDeletenuoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        btnDeletenuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        Icon = new ImageIcon("src/main/java/image/delete.png");
        resizeImg = Icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        resizedIcon = new ImageIcon(resizeImg);
        btnDeletenuoc.setIcon(resizedIcon);
        btnDeletenuoc.setText("Xóa");
        btnDeletenuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeletenuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeletenuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletenuocActionPerformed(evt);
            }
        });

        btnResetnuoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        btnResetnuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bx-reset-icon.png"))); // NOI18N
        Icon = new ImageIcon("src/main/java/image/bx-reset-icon.png");
        resizeImg = Icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        resizedIcon = new ImageIcon(resizeImg);
        btnResetnuoc.setIcon(resizedIcon);
        btnResetnuoc.setText("Reset");
        btnResetnuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResetnuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbtenNuoc = new JLabel();
        lbtenNuoc.setText("Tên Nước");
        lbtenNuoc.setHorizontalAlignment(SwingConstants.CENTER);
        lbtenNuoc.setFont(new Font("Arial", Font.BOLD, 14));
        lbtenNuoc.setBackground(new Color(153, 153, 255));

        lbBanso = new JLabel();
        lbBanso.setText("Bàn số:");
        lbBanso.setFont(new Font("Segoe UI", Font.BOLD, 12));

        // thiet lap drop down list cho ban
        ArrayList<Ban> dsBan = banDAO.getInstance().selectAll();
        String[] dsChonBan = new String[dsBan.size()];
        for (int i = 0; i < dsBan.size(); i++) {
            dsChonBan[i] = dsBan.get(i).getMaBan();
        }
        cbbban.setModel(new javax.swing.DefaultComboBoxModel<>(dsChonBan));

        javax.swing.GroupLayout gl_pannelQLnuoc = new javax.swing.GroupLayout(pannelQLnuoc);
        gl_pannelQLnuoc.setHorizontalGroup(
                gl_pannelQLnuoc.createParallelGroup(Alignment.LEADING)
                        .addGroup(gl_pannelQLnuoc.createSequentialGroup()
                                .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.LEADING, false)
                                        .addGroup(gl_pannelQLnuoc.createSequentialGroup()
                                                .addGap(12)
                                                .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.LEADING)
                                                        .addComponent(cbbtenNuoc, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbtenNuoc))
                                                .addGap(18)
                                                .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.LEADING)
                                                        .addComponent(lbSoluong, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tfSoluong, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(gl_pannelQLnuoc.createSequentialGroup()
                                                .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.LEADING)
                                                        .addGroup(gl_pannelQLnuoc.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(lbBanso, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(gl_pannelQLnuoc.createSequentialGroup()
                                                                .addGap(21)
                                                                .addComponent(cbbban, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18)
                                                .addComponent(btnAddnuoc, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)))
                                .addGap(12)
                                .addComponent(btnFixnuoc)
                                .addGap(18)
                                .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.LEADING)
                                        .addComponent(lbThanhtien)
                                        .addGroup(gl_pannelQLnuoc.createSequentialGroup()
                                                .addGap(10)
                                                .addComponent(btnDeletenuoc))
                                        .addComponent(lbGia, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                                .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.LEADING)
                                        .addGroup(gl_pannelQLnuoc.createSequentialGroup()
                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.TRAILING, false)
                                                        .addComponent(lbGiaVND, GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                                        .addComponent(lbThanhtienVND, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(gl_pannelQLnuoc.createSequentialGroup()
                                                .addGap(26)
                                                .addComponent(btnResetnuoc)))
                                .addContainerGap())
        );
        gl_pannelQLnuoc.setVerticalGroup(
                gl_pannelQLnuoc.createParallelGroup(Alignment.LEADING)
                        .addGroup(gl_pannelQLnuoc.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.TRAILING)
                                        .addGroup(gl_pannelQLnuoc.createSequentialGroup()
                                                .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.BASELINE)
                                                        .addComponent(lbSoluong, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lbtenNuoc, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE))
                                                .addGap(18))
                                        .addGroup(gl_pannelQLnuoc.createSequentialGroup()
                                                .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.BASELINE)
                                                        .addComponent(lbGiaVND, GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                                        .addComponent(lbGia))
                                                .addPreferredGap(ComponentPlacement.UNRELATED)))
                                .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(tfSoluong, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbbtenNuoc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbThanhtienVND, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbThanhtien))
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.LEADING)
                                        .addGroup(gl_pannelQLnuoc.createSequentialGroup()
                                                .addComponent(lbBanso, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                                .addGap(13)
                                                .addComponent(cbbban, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(gl_pannelQLnuoc.createParallelGroup(Alignment.BASELINE)
                                                .addComponent(btnDeletenuoc, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnFixnuoc, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnResetnuoc, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnAddnuoc, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE))
                                .addGap(28))
        );
        pannelQLnuoc.setLayout(gl_pannelQLnuoc);

        cbbtenNuoc.getAccessibleContext().setAccessibleName("");

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tên Nước");
        model.addColumn("Số lượng");
        model.addColumn("Giá Bán");
        model.addColumn("Thành Tiền");
        jTable1.setModel(model);

        spBangnuoc.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(Alignment.TRAILING)
                        .addGroup(Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(spBangnuoc, GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(spBangnuoc, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
        );
        jPanel3.setLayout(jPanel3Layout);

        lbTongtien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTongtien.setText("Tổng tiền:");

        lbTiennhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTiennhan.setText("Tiền nhận:");

        lbTienthua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTienthua.setText("Tiền thừa:");

        lbTongtienVND.setText("0 VNĐ");

        lbTienthuaVND.setText("0 VNĐ");

        txtTiennhan.setToolTipText("");
        txtTiennhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTiennhanActionPerformed(evt);
            }
        });

//        btnPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pay-Per-Click-icon.png"))); // NOI18N
        Icon = new ImageIcon("src/main/java/image/Pay-Per-Click-icon.png");
        resizeImg = Icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        resizedIcon = new ImageIcon(resizeImg);
        btnPay.setIcon(resizedIcon);
        btnPay.setText("Pay");
        btnPay.setToolTipText("");
        btnPay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

//        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer-icon.png"))); // NOI18N
        Icon = new ImageIcon("src/main/java/image/printer-icon.png");
        resizeImg = Icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        resizedIcon = new ImageIcon(resizeImg);
        btnPrint.setIcon(resizedIcon);
        btnPrint.setText("Print");
        btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

//        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Home-icon.png"))); // NOI18N
        Icon = new ImageIcon("src/main/java/image/Home-icon.png");
        resizeImg = Icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        resizedIcon = new ImageIcon(resizeImg);
        btnHome.setIcon(resizedIcon);
        btnHome.setText("Home");
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        lbStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Status-user-online-icon.png"))); // NOI18N
        Icon = new ImageIcon("src/main/java/image/Status-user-online-icon.png");
        resizeImg = Icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        resizedIcon = new ImageIcon(resizeImg);
        lbStatus.setIcon(resizedIcon);
        lbStatus.setText("Status");
        lbStatus.setToolTipText("");
        lbStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbStatus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbTienthua, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbTienthuaVND)
                                                        .addComponent(lbTongtienVND)))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(lbTiennhan, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtTiennhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lbTongtien)
                                                        .addComponent(lbTongtienVND))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lbTiennhan)
                                                        .addComponent(txtTiennhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(17, 17, 17)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lbTienthua)
                                                        .addComponent(lbTienthuaVND)))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))))
                                .addGap(75, 75, 75))
        );

        // set khung ngày giờ và tên nhân viên bên trái
        lbmaSoNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbmaSoNV.setText("Mã NV");
        lbHotennhanvien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHotennhanvien.setText("Tên NV");
        lbNgay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNgay.setText("Ngày:");
        lbThoigian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbThoigian.setText("Thời gian:");
        LocalDate currentDate = LocalDate.now();
        LocalDateTime currentDateTime = LocalDateTime.now();
        DateTimeFormatter formatTime = DateTimeFormatter.ofPattern("HH:MM a");
        String formattedTime = currentDateTime.format(formatTime);
        JLabel lbldate = new JLabel(currentDate.toString());
        lbldate.setFont(new Font("Tahoma", Font.PLAIN, 14));
        lbltime = new JLabel(formattedTime.toString());
        lbltime.setFont(new Font("Tahoma", Font.PLAIN, 14));

        ArrayList<nhanVien> listnhanVien1 = nhanVienDAO.getInstance().selectAll();
        String[] listNV1 = new String[listnhanVien1.size()];
        for (int i = 0; i < listnhanVien1.size(); i++) {
            listNV1[i] = listnhanVien1.get(i).getMaNV();
        }

        cbcmaNV = new JComboBox(new javax.swing.DefaultComboBoxModel<>(listNV1));
        JLabel lbltenNV = new JLabel();
        lbltenNV.setFont(new Font("Tahoma", Font.PLAIN, 14));
        cbcmaNV.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                String selectMaNV = (String) cbcmaNV.getSelectedItem();
                if (selectMaNV.isBlank()) {
                    lbltenNV.setText("");
                } else {
                    lbltenNV.setText(nhanVienDAO.getInstance().selectById(selectMaNV).getHoVaTen().toString());
                }

            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                                        .addComponent(lbNgay)
                                        .addComponent(lbThoigian)
                                        .addComponent(lbHotennhanvien)
                                        .addComponent(lbmaSoNV))
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                                        .addComponent(lbldate, GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(lbltime, GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                                .addGap(8))
                                        .addComponent(lbltenNV, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbcmaNV, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(lbmaSoNV)
                                        .addComponent(cbcmaNV, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(18)
                                                .addComponent(lbHotennhanvien))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                                .addComponent(lbltenNV, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)))
                                .addGap(9)
                                .addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(lbNgay)
                                        .addComponent(lbldate, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                                .addGap(19)
                                .addGroup(jPanel5Layout.createParallelGroup(Alignment.TRAILING)
                                        .addComponent(lbThoigian)
                                        .addComponent(lbltime, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
                                .addGap(38))
        );
        jPanel5.setLayout(jPanel5Layout);

        lbTrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        lbTrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Bàn trống.png"))); // NOI18N
        Icon = new ImageIcon("src/main/java/image/Bàn trống.png");
        resizeImg = Icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        resizedIcon = new ImageIcon(resizeImg);
        lbTrong.setIcon(resizedIcon);
        lbTrong.setText("Trống");
        lbTrong.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbTrong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbTrong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbKhachdat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        lbKhachdat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Khách đặt.png"))); // NOI18N
        Icon = new ImageIcon("src/main/java/image/Khách đặt.png");
        resizeImg = Icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        resizedIcon = new ImageIcon(resizeImg);
        lbKhachdat.setIcon(resizedIcon);
        lbKhachdat.setText("Khách đặt");
        lbKhachdat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbKhachdat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbDacokhach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        lbDacokhach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Đã có khách.png"))); // NOI18N
        Icon = new ImageIcon("src/main/java/image/Đã có khách.png");
        resizeImg = Icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        resizedIcon = new ImageIcon(resizeImg);
        lbDacokhach.setIcon(resizedIcon);
        lbDacokhach.setText("Đã có khách");
        lbDacokhach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbDacokhach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbDangchon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon = new ImageIcon("src/main/java/image/Đang được chọn.png");
        resizeImg = Icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        resizedIcon = new ImageIcon(resizeImg);
        lbDangchon.setIcon(resizedIcon);
//        lbDangchon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Đang được chọn.png"))); // NOI18N
        lbDangchon.setText("Đang chọn");
        lbDangchon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbDangchon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(34)
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbTrong, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
                                                .addGap(37)
                                                .addComponent(lbKhachdat, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                .addComponent(lbDacokhach, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                                .addComponent(lbDangchon, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(panel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                        .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbTieude)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(17)
                                                .addComponent(pannelQLnuoc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                                        .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbTieude, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                                .addGap(18)
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                                                        .addComponent(pannelQLnuoc, 0, 0, Short.MAX_VALUE)
                                                        .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, 189, Short.MAX_VALUE))
                                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 221, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
                                                .addGap(8))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                                                        .addComponent(lbTrong, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                                                                .addComponent(lbKhachdat, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(lbDacokhach, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(lbDangchon, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGap(18)
                                                .addComponent(panel1, GroupLayout.PREFERRED_SIZE, 465, GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
        );
        getContentPane().setLayout(layout);

        panel1.getAccessibleContext().setAccessibleName("Đặt bàn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

//     phương thức để nhấn enter khong bị loi
    public void tfSoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoluongActionPerformed

        String getTenNuoc = (String) cbbtenNuoc.getSelectedItem();
        float soLuong = Float.parseFloat(tfSoluong.getText());
        float giaBan = Float.parseFloat(String.valueOf(NuocUongDAO.getInstance().selectById(getTenNuoc).getGiaBan()));
        float thanhTien = soLuong * giaBan;

        if (getTenNuoc.equals(null)) {
            lbGiaVND.setText("0");
        } else {
            lbGiaVND.setText(String.valueOf(NuocUongDAO.getInstance().selectById(getTenNuoc).getGiaBan()));
            lbThanhtienVND.setText(String.valueOf(thanhTien));
        }
    }

    private void cbbLoainuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoainuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoainuocActionPerformed

    private void btnAddnuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddnuocActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (model.getColumnCount() == 0) {
            model.addColumn("Tên Nước");
            model.addColumn("Số lượng");
            model.addColumn("Giá Bán");
            model.addColumn("Thành Tiền");
        }

        Object[] newrow = {cbbtenNuoc.getSelectedItem(), tfSoluong.getText(), lbGiaVND.getText(), lbThanhtienVND.getText()};
        model.addRow(newrow);
        ResetTable();

    }//GEN-LAST:event_btnAddnuocActionPerformed

    private void tfTiennhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTiennhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTiennhanActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
                dispose();
                MenuFr.main(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnDeletenuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletenuocActionPerformed

        int select = jTable1.getSelectedRow();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.removeRow(select);
        jTable1.setModel(model);
        JOptionPane.showMessageDialog(null, "Xóa thành Công");

        jTable1.revalidate();
        jTable1.repaint();
    }

    ;
    
	private void btnReSet(ActionEvent e) {
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa tất cả ?");
        if (confirm == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            lbTongtienVND.setText("0");
            lbTienthuaVND.setText("0");
            txtTiennhan.setText("0");

        }

    }

    public void ResetTable() {

        Float sum = (float) 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            String textValue = (String) (jTable1.getValueAt(i, 3).toString().replaceAll("[ VNĐ]", "")).replaceAll(",", "");

            Float value = Float.parseFloat(textValue);
            sum = sum + value;
        }
        lbTongtienVND.setText(String.valueOf(sum));

    }

    private void btnFixnuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixnuocActionPerformed

        int select = jTable1.getSelectedRow();
        if (select != -1) {
            jTable1.setValueAt(cbbtenNuoc.getSelectedItem(), select, 0);
            jTable1.setValueAt(tfSoluong.getText(), select, 1);
            jTable1.setValueAt(lbGiaVND.getText(), select, 2);
            jTable1.setValueAt(lbThanhtienVND.getText(), select, 3);
            JOptionPane.showMessageDialog(null, "Đã cật nhập dữ liệu thành công");
        }
        ResetTable();
    }//GEN-LAST:event_btnFixnuocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHangFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHangFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHangFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanHangFr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pannelQLnuoc;
    private javax.swing.JButton btnAddnuoc;
    private javax.swing.JButton btnDeletenuoc;
    private javax.swing.JButton btnFixnuoc;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnResetnuoc;
    private javax.swing.JComboBox<String> cbbtenNuoc;
    private javax.swing.JComboBox<String> cbbban;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbmaSoNV;
    private javax.swing.JLabel lbDacokhach;
    private javax.swing.JLabel lbDangchon;
    private javax.swing.JLabel lbGia;
    private javax.swing.JLabel lbGiaVND;
    private javax.swing.JLabel lbHotennhanvien;
    private javax.swing.JLabel lbKhachdat;
    private javax.swing.JLabel lbNgay;
    private javax.swing.JLabel lbSoluong;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbThanhtien;
    private javax.swing.JLabel lbThanhtienVND;
    private javax.swing.JLabel lbThoigian;
    private javax.swing.JLabel lbTiennhan;
    private javax.swing.JLabel lbTienthua;
    private javax.swing.JLabel lbTienthuaVND;
    private javax.swing.JLabel lbTieude;
    private javax.swing.JLabel lbTongtien;
    private javax.swing.JLabel lbTongtienVND;
    private javax.swing.JLabel lbTrong;
    private javax.swing.JPanel panel1;
    private javax.swing.JScrollPane spBangnuoc;
    private javax.swing.JTextField tfSoluong;
    private javax.swing.JTextField txtTiennhan;
    private JLabel lbtenNuoc;
    private JLabel lbban1;
    private JLabel lbltime;
    private JComboBox cbcmaNV;
    private JLabel lbBanso;
    private JLabel lbtenNV;
    private ImageIcon Icon;
    private Image resizeImg;
    private ImageIcon resizedIcon;
}
